# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  wunderlist-to-taskwarrior-benchmarks:
    dependencies:
    - base
    - wunderlist-to-taskwarrior
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: Fetch your tasks from Wunderlist and add them to TaskWarrior
executables:
  wunderlist-to-taskwarrior:
    dependencies:
    - base
    - wunderlist-to-taskwarrior
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: mafagafogigante/wunderlist-to-taskwarrior
library:
  dependencies:
  - aeson
  - aeson-pretty
  - base
  - bytestring
  - clock
  - containers
  - directory
  - exceptions
  - filepath
  - formatting
  - http-client
  - http-conduit
  - monad-control
  - monad-logger
  - persistent
  - persistent-sqlite
  - persistent-template
  - process
  - text
  source-dirs: library
license: MIT
maintainer: Bernardo Sulzbach
name: wunderlist-to-taskwarrior
synopsis: Fetch your tasks from Wunderlist and add them to TaskWarrior
tests:
  wunderlist-to-taskwarrior-test-suite:
    dependencies:
    - base
    - wunderlist-to-taskwarrior
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
